  version: "3.7"
  services:
    web:
      image: nginx
      volumes:
        - ./site/index.html:/usr/share/nginx/html/index.html
      ports:
        - "80:80" 
        

  
  
  # mqtt5 eclipse-mosquitto
    mqtt5:
      image: eclipse-mosquitto
      container_name: mqtt5
      ports:
        - "1884:1884" #default mqtt port
      volumes:
        - ./config:/mosquitto/config:rw
        - ./data:/mosquitto/data:rw
        - ./log:/mosquitto/log:rw
      restart: unless-stopped

    # volumes for mapping data,config and log
  volumes:
   config:
   data:
   log:
 
  networks:
   default:
     name: mqtt5-network



        
  
       