  version: "3.7"
  services:
    web:
      image: nginx
      container_name: nginx
      volumes:
        - ./site/index.html:/usr/share/nginx/html/index.html
        - ./site/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - ./certificates/:/etc/nginx/certs/
      ports:
        - "443:443"
        - "80:80"
      
        
  # mqtt5 eclipse-mosquitto
    mqtt5:
      image: eclipse-mosquitto
      container_name: mqtt5
      ports:
        - "1883:1883"
        - "1884:1884" 
      volumes:
        - ./config:/mosquitto/config:rw
        - ./data:/mosquitto/data:rw
        - ./log:/mosquitto/log:rw
      restart: unless-stopped

    # volumes for mapping data,config and log




        
  
       